---
  - hosts: lb
    remote_user: moti
    become: true	#give sudo privilege
    tasks:
      - name: Install nginx webserver
        apt:
          name: nging 
          state: present 
          update_cache: yes



